# This is a basic workflow to help you get started with Actions

name: class4(hooks)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Node installation
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          version: 12
   
       # yarn install
  
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install 
          
          
      # yarn build
      - name: build through yarn
        run: yarn build
        
      #surge installation
      - name: install surge
        run: npm install -g surge
      
      
      #surge depoly
      - name: surge deploy
        run: surge ./build  http://class5context-api.surge.sh/ --token ${{secrets.surge_key}}
      
          
          
           
       
       
       
              
       
 
       
            
       
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
